global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets:
          - "ip target:9100"   # IP target

  - job_name: 'crud-backend'
    static_configs:
      - targets:
          - "ip target:5000"   # IP target

  - job_name: 'postgres'
    static_configs:
      - targets:
          - "ip target:9187"   # IP target
