global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "node"
    static_configs:
      - targets:
          - "172.17.131.196:9100"   # IP WSL 2

  - job_name: 'crud-backend'
    static_configs:
      - targets:
          - "172.17.131.196:5000"   # IP WSL 2

  - job_name: 'postgres'
    static_configs:
      - targets:
          - "172.17.131.196:9187"   # IP WSL 2
