version: '3.9'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"  # Port eksternal untuk Nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - frontend_network
      - backend_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000"  # Mengganti port internal dan eksternal menjadi 5000
    depends_on:
      - db
    networks:
      - frontend_network
      - backend_network
      - monitoring_network

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend_network
      - monitoring_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"  # Port default untuk Node Exporter
    networks:
      - monitoring_network

networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
  monitoring_network:
    external: true

volumes:
  db_data:
    driver: local
